### ISSUE TITLE
Double id

### ISSUE THREAD

**Issue by CarlMichelsen** [fejl40/fejl40.github.io#11]
Checkbox and smokeholder has same id :(
![image](https://user-images.githubusercontent.com/29626285/182852683-f9e41cf4-8aed-4e41-8fd5-667c75cb6300.png)

**Comment by asdf-dev** [comment]
fremhævet fil [T_CT.jpg](https://github.com/fejl40/fejl40.github.io/blob/main/public/maps/mirage/T_CT.jpg). Jeg er ikke sikker på jeg forstår problemet - Den smoker jo CT, og Terrorist er correct checked
